name: Debug

on:
  push:
    paths:
      - "*"

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run debug script
        run: |
          pwd
          ls -R
